# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/uart/uart.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==uart || ORIG_REF_NAME==uart} -quiet] -quiet

# IP: bd/uart/ip/uart_processing_system7_0_0/uart_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==uart_processing_system7_0_0 || ORIG_REF_NAME==uart_processing_system7_0_0} -quiet] -quiet

# IP: bd/uart/ip/uart_proc_sys_reset_0_0/uart_proc_sys_reset_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==uart_proc_sys_reset_0_0 || ORIG_REF_NAME==uart_proc_sys_reset_0_0} -quiet] -quiet

# XDC: c:/s4projetVivado/uart/uart.gen/sources_1/bd/uart/uart_ooc.xdc
