# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/s4projetVivado/uart/uart.srcs/sources_1/bd/uart/ip/uart_processing_system7_0_0/uart_processing_system7_0_0.xci
# IP: The module: 'uart_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/s4projetVivado/uart/uart.gen/sources_1/bd/uart/ip/uart_processing_system7_0_0/uart_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'uart_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/s4projetVivado/uart/uart.srcs/sources_1/bd/uart/ip/uart_processing_system7_0_0/uart_processing_system7_0_0.xci
# IP: The module: 'uart_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/s4projetVivado/uart/uart.gen/sources_1/bd/uart/ip/uart_processing_system7_0_0/uart_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'uart_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
