domain_path: C:\Xilinx\Vivado\2024.1\data\boards\board_files\zybo-z7-10\platform_main\zynq_fsbl\zynq_fsbl_bsp
app_src_dir: C:\Xilinx\Vitis\2024.1\data\embeddedsw\lib\sw_apps\zynq_fsbl
template: zynq_fsbl
